#!/usr/bin/python3

# must be run as root/admin user

import random
import subprocess
import time
import os

config_dir = "/vpn/config"
config_files = [f"{config_dir}/config{i}.ovpn" for i in range(1, 21)]
used_configs = []
timeout = 30
exit_code = 1

while len(used_configs) < len(config_files):
    config_file = random.choice(list(set(config_files) - set(used_configs)))
    used_configs.append(config_file)
    print("Trying {}...".format(config_file))
    proc = subprocess.Popen(["openvpn", "--config", config_file])
    time.sleep(timeout)
    if proc.poll() is None:
        os.system("pkill -f {}".format(config_file))
        print("Connection to {} failed.".format(config_file))
    else:
        print("Connected to {}!".format(config_file))
        exit_code = 0
        break

exit(exit_code)
